In [1]:
import jax, jax.numpy as jnp

from untangle.algorithm import cmtf_ssd
from untangle.scaler import JacobianScaler
from untangle.utils import collect_information, function_error

key = jax.random.key(0)

In [2]:
def f(x):
    return jnp.array([
        jnp.sin(4*jnp.pi*x[0]) + x[1],
        jnp.cos(3*jnp.pi*x[1]) * x[0]
    ])

m = 2
n = 2
N = 100
rank = 2

In [3]:
X, Y, J = collect_information(f, N, m, key=key)

scaler = JacobianScaler(J, Y)
J_scaled, Y_scaled = scaler.scale()

In [4]:
learned_scaled = cmtf_ssd(X, Y_scaled, J_scaled, rank, lam=1.0, key=key, iterations=20)
learned = scaler.unscale(learned_scaled)

Computing CMTF-SSD:   0%|                                                          | 0/20 [00:00<?, ?it/s]

196.0861106654189
548.7009240899757


Computing CMTF-SSD:   5%|██▌                                               | 1/20 [00:00<00:18,  1.01it/s]

4.5400231389177105e-05
4.5400231389177105e-05


Computing CMTF-SSD:  10%|█████                                             | 2/20 [00:01<00:10,  1.70it/s]

4.5400094723946384e-05
4.540019065711943e-05


Computing CMTF-SSD:  15%|███████▌                                          | 3/20 [00:01<00:07,  2.23it/s]

4.5400207041367536e-05
0.00023812702921292668


Computing CMTF-SSD:  20%|██████████                                        | 4/20 [00:01<00:06,  2.58it/s]

4.540014205482245e-05
0.0003265201510574395


Computing CMTF-SSD:  25%|████████████▌                                     | 5/20 [00:02<00:05,  2.51it/s]

4.540016524924028e-05
0.00010601997363610776


Computing CMTF-SSD:  30%|███████████████                                   | 6/20 [00:02<00:05,  2.76it/s]

4.540016535262976e-05
0.00013672994061485422


Computing CMTF-SSD:  35%|█████████████████▌                                | 7/20 [00:02<00:04,  2.94it/s]

4.540016526821069e-05
0.00014594651469345129


Computing CMTF-SSD:  40%|████████████████████                              | 8/20 [00:03<00:03,  3.08it/s]

4.5400165226677865e-05
0.00014862015848252755


Computing CMTF-SSD:  45%|██████████████████████▌                           | 9/20 [00:03<00:03,  3.17it/s]

4.540016526126941e-05
0.00014945316794511788


Computing CMTF-SSD:  50%|████████████████████████▌                        | 10/20 [00:03<00:03,  2.97it/s]

4.540016529443278e-05
0.0001496939270884203


Computing CMTF-SSD:  55%|██████████████████████████▉                      | 11/20 [00:04<00:02,  3.12it/s]

4.5400165170038256e-05
0.0001498604799818032


Computing CMTF-SSD:  60%|█████████████████████████████▍                   | 12/20 [00:04<00:02,  2.83it/s]

4.5400165199223806e-05
0.00014960204678944047


Computing CMTF-SSD:  65%|███████████████████████████████▊                 | 13/20 [00:04<00:02,  2.95it/s]

4.5400165195163395e-05
0.00014986165787538697


Computing CMTF-SSD:  70%|██████████████████████████████████▎              | 14/20 [00:05<00:01,  3.03it/s]

4.540016527488091e-05
0.00014972916917908703


Computing CMTF-SSD:  75%|████████████████████████████████████▊            | 15/20 [00:05<00:01,  3.10it/s]

4.5400165243805895e-05
0.0001499431924515989


Computing CMTF-SSD:  80%|███████████████████████████████████████▏         | 16/20 [00:05<00:01,  3.15it/s]

4.540016525340916e-05
0.0001498525015025945


Computing CMTF-SSD:  85%|█████████████████████████████████████████▋       | 17/20 [00:06<00:00,  3.18it/s]

4.540016528552953e-05
0.0001498045031041479


Computing CMTF-SSD:  90%|████████████████████████████████████████████     | 18/20 [00:06<00:00,  3.15it/s]

4.540016516732328e-05
0.0001498616029214098


Computing CMTF-SSD:  95%|██████████████████████████████████████████████▌  | 19/20 [00:06<00:00,  3.16it/s]

4.540016528199913e-05
0.0001499184353068217


Computing CMTF-SSD: 100%|█████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.77it/s]


In [8]:
learned_scaled.factors

(Array([[ 0.03475678,  0.00706463],
        [ 0.00042822, -0.17957266]], dtype=float32),
 Array([[-0.9998748 ,  0.00378442],
        [-0.01582877, -0.99999285]], dtype=float32),
 Array([[-44.986134  ,  -1.7850001 ],
        [ 29.31392   ,   9.102492  ],
        [-38.32398   , -10.648921  ],
        [ 40.38229   ,  -1.8215904 ],
        [ 57.924244  , -10.492343  ],
        [-54.88276   ,  -2.7242434 ],
        [ 11.234281  ,   8.006145  ],
        [-19.860588  ,  -5.321162  ],
        [ 25.989664  ,  -4.69503   ],
        [-56.918304  ,  -3.1160507 ],
        [-50.354107  ,  -3.214187  ],
        [-54.323856  ,  -7.855278  ],
        [-43.680313  ,   4.9107475 ],
        [-14.501887  ,  -6.659696  ],
        [ 49.556503  ,  -6.657395  ],
        [-39.023373  ,   4.1649137 ],
        [-56.700478  ,   8.582096  ],
        [-26.714672  ,   8.922658  ],
        [ 48.121975  ,  -8.649098  ],
        [-56.750965  ,   8.257056  ],
        [ 36.187782  ,  -7.078061  ],
        [  7.1948996 ,  

In [5]:
learned(X[1]), f(X[1])

(Array([-0.6742006 ,  0.25189245], dtype=float32),
 Array([-0.39073694, -0.09670348], dtype=float32))

In [6]:
function_error(f, learned, X)

Array([ 57.79824, 107.61058], dtype=float32)